"""user_name ->> name

Revision ID: 3a9a138979ed
Revises: 86a53fe7cfdb
Create Date: 2025-02-05 11:18:26.944114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a9a138979ed"
down_revision: Union[str, None] = "86a53fe7cfdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(length=20), nullable=False)
    )
    op.drop_column("users", "user_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_name",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###
