"""create task table

Revision ID: 4770e3ff331a
Revises: 04370d7a7e6e
Create Date: 2025-01-20 11:12:29.794184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4770e3ff331a"
down_revision: Union[str, None] = "04370d7a7e6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("title", sa.String(), nullable=False))
    op.drop_column("tasks", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "title")
    # ### end Alembic commands ###
